# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b395d1c78946bdaae00548fdf45bffabf7bb9ee54181c23ca7913fbc91a8eb962e39e085ce800397eb6941c93e1ec000e492c7da31c60a5a747400423a6cab9

test:
  secret_key_base: 3c161ee24add6224231978a49c4faf5d64c0933636815d8c15dcdc071b9a641c01603131df4819e39c6753828c49a26e98ed37c2e3ac990464f55792910ff3de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
